# Generated by Django 4.2.15 on 2024-08-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tacticalstyle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tacticalstyle',
            name='name',
        ),
    ]
